import json
from app.main import app

def export_artists_spec():
    # Get the full specification generated by FastAPI
    full_spec = app.openapi()
    
    # Create a new, clean dictionary just for the Record Label
    artists_spec = {
        "openapi": "3.1.1",
        "info": {
            "title": "Record Label API (Artists)",
            "version": "3.1.1"
        },
        "paths": {},
        "components": {
            "schemas": {},
            # Keep the Basic Auth security scheme
            "securitySchemes": full_spec["components"].get("securitySchemes", {})
        }
    }
    
    # 1. Copy ONLY the paths that start with /artists
    for path, path_item in full_spec["paths"].items():
        if path.startswith("/artists"):
            artists_spec["paths"][path] = path_item
            
    # 2. Copy ONLY the schemas (DTOs) that have "Artist" in their name
    for schema_name, schema_val in full_spec["components"]["schemas"].items():
        if "Artist" in schema_name or "ValidationError" in schema_name:
            artists_spec["components"]["schemas"][schema_name] = schema_val
            
    # Save it to a brand new file
    with open("artists_openapi.json", "w") as f:
        json.dump(artists_spec, f, indent=2)
        
    print("Successfully created artists_openapi.json!")

if __name__ == "__main__":
    export_artists_spec()